apiVersion: v1
kind: PersistentVolume
metadata:
  name: ml-service-pv
spec:
  capacity:
    storage: 1Gi
#  accessModes:
#    - ReadWriteOnce
  hostPath:
    path: /data/ml-service

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ml-service-statefulset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-service
  template:
    metadata:
      labels:
        app: ml-service
    spec:
      containers:
        - name: ml-service
          image: registry:dev
          volumeMounts:
            - name: ml-service-pv
              mountPath: /app/data
      volumes:
        - name: ml-service-pv
          persistentVolumeClaim:
            claimName: ml-service-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-service-pvc
spec:
#  accessModes:
#    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
